pipeline {
  agent any

  environment {
    APP        = 'eureka-server'              // module folder name
    IMAGE_APP  = 'eureka-server'              // container/deployment name
    REGISTRY   = 'docker.io/udawat'
    IMAGE_REPO = "${REGISTRY}/${IMAGE_APP}"
    KUBECONFIG = '/var/lib/jenkins/.kube/config'
  }

  stages {
    stage('Build Application') {
      steps {
        dir("${APP}") {
          sh 'chmod +x mvnw'
          sh './mvnw -q clean package -DskipTests'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("${APP}") {
          sh "docker build -t ${IMAGE_APP}:latest ."
        }
      }
    }

    stage('Tag & Push Image to Docker Hub') {
      steps {
        script {
          env.IMAGE_TAG = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        }
        withCredentials([usernamePassword(credentialsId: 'DOCKER_HUB_CREDS', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh """
            echo "$PASS" | docker login docker.io -u "$USER" --password-stdin
            docker tag ${IMAGE_APP}:latest ${IMAGE_REPO}:${IMAGE_TAG}
            docker tag ${IMAGE_APP}:latest ${IMAGE_REPO}:latest
            docker push ${IMAGE_REPO}:${IMAGE_TAG}
            docker push ${IMAGE_REPO}:latest
          """
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        dir("${APP}") {
          sh """
            set -e
            kubectl apply -f ${IMAGE_APP}-deployment.yaml
            kubectl set image deployment/${IMAGE_APP} ${IMAGE_APP}=${IMAGE_REPO}:${IMAGE_TAG}
            kubectl rollout status deployment/${IMAGE_APP} --timeout=180s
          """
        }
      }
    }
  }

  post {
    always {
      sh 'docker image prune -f || true'
    }
  }
}
