apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: product-service:latest
        imagePullPolicy: IfNotPresent # Important for using local Minikube images
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  type: NodePort # Exposes the service outside the cluster for testing
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
